### PR TITLE
Update to SDK V12 and add ETag and Last Modified support

### PR DESCRIPTION
**Pull request by nzdev**
https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/issues/175

Updates to Azure Storage SDK V12.
Adds ETag and Last Modified Support
Removes Automapper, mysql and XMLRPC as they are unused.

### CODE REVIEW

**Comment by Jeavon** [comment]
@nzdev This is a great start! Do you intend to continue it?

**Comment by nzdev** [comment]
It may be a very long time before I come back to this. To my knowledge this works. The only thing not implemented is sas token support. If someone adds this then it's complete.

**Comment by nzdev** [comment]
https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/issues/170 added

**Comment by Jeavon** [comment]
@nzdev this is looking awesome! Great work!

**Pull request closed without merging**
