### PR TITLE
Added support for Azure Key Vault Storage in Umbraco 7

### PR DESCRIPTION
**Pull request by RachBreeze**
Hello,

This PR adds support for Azure Key Vault in Umbraco 7, it is based on #182

### CODE REVIEW

**Comment by Jeavon** [comment]
@RachBreeze Any idea what the conflicts are?

**Comment by RachBreeze** [comment]
Hi @Jeavon erm I think I'm merging to the wrong branch https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/pull/190/commits/dc725bebc0b0a097f92dfa7ec83826f51bb3e496 says into develop-umbraco-version-8. Not into v7. Let me see if I can fix this, if not  I may need to make a new PR

**Comment by RachBreeze** [comment]
Hi @Jeavon I have made that change, I apologise for not checking the branch I was making the PR back into

**Comment by RachBreeze** [comment]
Hi @Jeavon 
Is everything ok with this? We have a client on Umbraco 7 who would like to use this functionality

Thank you

Rachel

**Comment by Jeavon** [comment]
@RachBreeze Looks good, just firing up the v1 pipelines, it's been a while!

**Comment by Jeavon** [comment]
If you want to test, it's available on MyGet, will release to NuGet next week

`Install-Package UmbracoFileSystemProviders.Azure -Version 1.2.0-alpha-000443 -Source https://www.myget.org/F/umbraco-packages/api/v3/index.json`

**Comment by RachBreeze** [comment]
Hi @Jeavon  amazing thank you

**Comment by Jeavon** [comment]
Released in v1.2 - thanks again @RachBreeze

**Pull request merged**
